### PR TITLE
Fix example check

### PR DESCRIPTION
**Pull request by saulecabrera**

### CODE REVIEW

**Comment by squillace** [comment]
Hey @saulecabrera, can I help out in some way? I'd love to get this running again.

**Comment by saulecabrera** [comment]
@squillace Yeah,  I'd appreciate any help investigating. I tried a couple of things but I'm running out of ideas and I don't have a linux machine to try this out locally. The weird thing is that this started failing with https://github.com/bytecodealliance/spidermonkey-wasm-rs/pull/39 which is totally unrelated to any of the CI checks. Locally doesn't fail either though (using macOS).

**Comment by seddonm1** [comment]
@saulecabrera the short term fix is to force the `promptly` version in the `crates/repl-example/Cargo.toml`

```
promptly = "=0.3.0"
```

From my digging it looks like https://github.com/yoshuawuyts/fd-lock relies on some features that were removed in one of the more recent Rust releases.

**Comment by saulecabrera** [comment]
Hey @seddonm1, thanks for looking into this. Your suggestion fixed it!

**Comment by yoshuawuyts** [comment]
> From my digging it looks like https://github.com/yoshuawuyts/fd-lock relies on some features that were removed in one of the more recent Rust releases.

@seddonm1 I was just made aware about this issue. Do you have any more details on how you're seeing `fd-lock` fail? I'm trying to reproduce the failure you're describing, and I'm not having any luck.

**Comment by seddonm1** [comment]
@yoshuawuyts I'm sorry, this is beyond my level of understanding of what is going on without far more time.

**Pull request merged**
